#!/bin/env python

'''
generates figures used in the paper
'''
import matplotlib.pyplot as plt
import numpy as np
from os.path import join
import ipdb as pdb

def plot_val_loss(data_dir):
	# single test
  tmp = np.load(join(data_dir,'e2c-val-loss.npz'))
  L_mean=tmp['mean'] # mean validation loss
  L_std=tmp['std'] # std validation loss
  T = range(L_mean.size)
  plt.errorbar(T[::4], L_mean[::4], L_std[::4],label='validation loss')
  L_train=np.load(join(data_dir,'l_hist.npy'))
  plt.plot(range(2,L_mean.size),L_train[200::100],label='train loss') # minibatch length
  plt.ylim([0,400])
  plt.xlabel('Episode')
  plt.legend()
  return

if __name__ == '__main__':
	# data needs to be generated by plane_analyze.py first
	#data_dir='/ltmp/e2c-plane3-adaptive'
	data_dir='/ltmp/e2c-plane3-rand/'
	plot_val_loss(data_dir)
	plt.savefig('rand_post.png')
	plt.show()
